version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: homepage_web_1
      APP_PORT: $APP_HOMPAGE_PORT
  
  web:
    image: ghcr.io/benphelps/homepage:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - APP_HOMPAGE_PORT:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/config:/app/config
